site_name: PQM Dashboard Web Application Documentation
site_url: https://sitename.example
theme:
  name: material
  icon:
    logo: material/view-dashboard
  favicon: assets/combined_logo.png
  features:
    - navigation.footer
    - search.highlight
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: blue

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: deep purple
      accent: blue

plugins:
  # - glightbox
  - search

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  # for images:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  # for admonitions
  - admonition
  - pymdownx.details

# extra:
  # put website link here
  # social:
  #   - icon: material/view-dashboard
  #     link: https://youtube.com/@james-willett
copyright: Copyright &copy; 2025 Jessica Zonneveld